export const jobs = [
  { 
    id: 1,
    company: 'Lutron Electronics',
    link: 'https://commercial.lutron.com/us/en/whole-building-systems/athena',
    title: 'Software Engineer Intern',
    date: 'May 2023 - Aug 2023',
    skills: 'React, TypeScript, AWS cloud services, Jest unit testing',
  },
  { 
    id: 2,
    company: 'GeoSpatial Innovations, Inc.',
    link: 'https://gsiworks.com/',
    title: 'Software Engineer Intern',
    date: 'May 2022 - May 2023',
    skills: 'ArcGIS, JavaScript, PowerShell scripting, RestAPI services',
  },
  { 
    id: 3,
    company: 'SOC 119, Dr. Sam Richards',
    link: 'https://www.soc119.org/',
    title: 'Technical Specialist',
    date: 'Aug 2021 - Present',
    skills: 'Manage and run in-class podium and YouTube stream production',
  },
  { 
    id: 4,
    company: 'HackPSU',
    link: 'https://hackpsu.org',
    title: 'Marketing Director',
    date: 'Jan 2022 - Present',
    skills: 'Content creation, social media & team management for PSU\'s fully student-run hackathon',
  },
  { 
    id: 5,
    company: 'Women in Engineering',
    link: 'https://inclusion.engr.psu.edu/student-programs/women-in-engineering-program/index.aspx',
    title: 'Mathematics Facilitator',
    date: 'Jan 2022 - May 2023',
    skills: 'Mentored 20+ underclassmen in math courses each semester',
  },
  { 
    id: 6,
    company: 'Lion Line',
    link: 'https://directory.alumni.psu.edu/s/1218/alumni/index.aspx?sid=1218&gid=4&pgid=379',
    title: 'Student Caller',
    date: 'Oct 2021 - May 2022',
    skills: 'Fundraised $12,000+ for THON and other organizations at PSU',
  },
];
