export const blogs = [
  {
    slug: "/blog/description-of-sdlc",
    title: "The Software Development Life Cycle",
    header: "A high-level description of the Software Development Life Cycle (SDLC) and its relevance to this website.",
    date: "1st April, 2024",
    readtime: "10 minute",
    visibility: "",
    tags: ["Software Development"],
  },
  {
    slug: "/blog/git-basics",
    title: "Git & GitHub Basics",
    header: "The basics of Git and GitHub highlighted by me using tips, tutorials, and insights.",
    date: "11th June, 2024",
    readtime: "8 minute",
    visibility: "",
    tags: ["Software Development", "Git"],
  },
  {
    slug: "/blog/understanding-the-developers-mind",
    title: "Understanding The Developer's Mind",
    header: "A high-level psychological summary of the brain of a software developer, compiled using my knowledge of neuroscience.",
    date: "29th March, 2024",
    readtime: "10 minute",
    visibility: "invisible",
    tags: ["Psychology", "Software"],
  },
  {
    slug: "/blog/the-art-of-attention",
    title: "The Art of Attention",
    header: "A portfolio of my creations of user-focused, captivating, and engaging graphic design for HackPSU marketing material through Canva",
    date: "28th Februrary, 2024",
    readtime: "10 minute",
    visibility: "invisible",
    tags: ["Graphic Design", "Marketing", "UI/UX"],
  },
  {
    slug: "blog-3",
    title: "Blog 3",
    header: "A portfolio of my creations of user-focused, captivating, and engaging graphic design for HackPSU marketing material through Canva",
    date: "16th Februrary, 2024",
    readtime: "10 minute",
    visibility: "invisible",
    tags: [""],
  },
  {
    slug: "blog-4",
    title: "Blog 4",
    header: "A psychological deep dive into how the brain of a software developer works",
    date: "11th September, 2024",
    readtime: "10 minute",
    visibility: "invisible",
    tags: [""],
  },
  {
    slug: "blog-5",
    title: "Blog 5",
    header: "A portfolio of my creations of user-focused, captivating, and engaging graphic design for HackPSU marketing material through Canva",
    date: "21st September, 2024",
    readtime: "10 minute",
    visibility: "invisible",
    tags: [""],
  },
  {
    slug: "blog-6",
    title: "Blog 6",
    header: "A psychological deep dive into how the brain of a software developer works",
    date: "11th May, 2024",
    readtime: "10 minute",
    visibility: "invisible",
    tags: [""],
  },
  {
    slug: "the-art-of-attention",
    title: "The Art of Attention",
    header: "A portfolio of my creations of user-focused, captivating, and engaging graphic design for HackPSU marketing material through Canva",
    date: "28th Februrary, 2024",
    readtime: "10 minute",
    visibility: "invisible",
    tags: [""],
  },
  {
    slug: "understanding-the-developers-mind",
    title: "Understanding the Developer's Mind",
    header: "A psychological deep dive into how the brain of a software developer works",
    date: "11th March, 2024",
    readtime: "10 minute",
    visibility: "invisible",
    tags: [""],
  },
  {
    slug: "blog-3",
    title: "Blog 3",
    header: "A portfolio of my creations of user-focused, captivating, and engaging graphic design for HackPSU marketing material through Canva",
    date: "16th Februrary, 2024",
    readtime: "10 minute",
    visibility: "invisible",
    tags: [""],
  },
  {
    slug: "blog-4",
    title: "Blog 4",
    header: "A psychological deep dive into how the brain of a software developer works",
    date: "11th September, 2024",
    readtime: "10 minute",
    visibility: "invisible",
    tags: [""],
  },
  {
    slug: "blog-5",
    title: "Blog 5",
    header: "A portfolio of my creations of user-focused, captivating, and engaging graphic design for HackPSU marketing material through Canva",
    date: "21st September, 2024",
    readtime: "10 minute",
    visibility: "invisible",
    tags: [""],
  },
  {
    slug: "blog-6",
    title: "Blog 6",
    header: "A psychological deep dive into how the brain of a software developer works",
    date: "11th May, 2024",
    readtime: "10 minute",
    visibility: "invisible",
    tags: [""],
  },
];

export const blogBlurb = "Welcome to my blog! I created this space on the internet for me to express my thoughts as I grow to travel and experience the world, face new challenges, or find things that fascinate me.\nI hope you like reading these as much as I liked writing them. "
